# Set base image (host OS)
FROM amazon/aws-iot-greengrass:latest

# Set one or more individual labels
LABEL version="0.0.1-beta"
LABEL author="muutttu@live.fi"

ENTRYPOINT [ "/greengrass-entrypoint.sh" ]