version: '3'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: ggc-stack/webapp:0.1-beta
    network_mode: bridge
    ports:
      - 5000:5000
    restart: on-failure
