version: '3'

services:
  web:
    container_name: flask-app
    build:
      context: ./web
      dockerfile: Dockerfile
    image: ggc-stack/webapp:0.1-beta
    networks:
      - ggcnetwork
    restart: on-failure

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: ggc-stack/wwwproxy:0.1-beta
    networks:
      - ggcnetwork
    expose:
      - "8080"
    ports:
      - "80:8080"
    restart: on-failure

  ggc:
    init: true
    container_name: aws-iot-greengrass
    build:
      context: ./ggc
      dockerfile: Dockerfile
    image: ggc-stack/aws-iot-greengrass:2.1.0
    volumes:
      - /iot-aws-ggc-stack/services/ggc/certs:/greengrass/certs
      - /iot-aws-ggc-stack/services/ggc/config:/greengrass/config
      - /iot-aws-ggc-stack/services/ggc/credentials:/root/.aws/:ro
    networks:
      - ggcnetwork
    ports:
      - "8883:8883"
    restart: on-failure

networks:
  ggcnetwork: