version: '3'

services:
  web:
    container_name: flask_app
    build:
      context: ./web
      dockerfile: Dockerfile
    image: ggc-stack/webapp:0.1-beta
    #network_mode: bridge
    networks:
      - ggcnetwork
    expose:
      - "5000"
    ports:
      - 5000:5000
    restart: on-failure

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: ggc-stack/wwwproxy:0.1-beta
    networks:
      - ggcnetwork
    expose:
      - "8080"
    ports:
      - "80:8080"
    restart: on-failure

networks:
  ggcnetwork: